config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])

    if @flat.update(flat_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to root_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Simple Airbnb</a>
  <div class="ml-auto">
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
  </div>
</nav>

<div class="container">
  <%= simple_form_for @flat do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>
  <div class="form-actions">
    <%= f.submit 'Edit', class: 'btn btn-primary' %>
  </div>
  <% end %>
</div>

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand">Simple Airbnb</a>
  <div class="ml-auto">
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
  </div>
</nav>

<div class="container">
  <h1>All our Flats(<%= Flat.count%>)</h1>
  <div class="grid-flat">
    <% @flats.each do |flat| %>
        <div class="flat card">
          <div class="info">
            <div class="titre text-center pt-2">
              <h3><%= flat.name %></h3>
              <p><%= flat.description %></p>
            </div>
            <div class="info-icone">
              <div class="guest">
                <i class="fas fa-users"></i>
                <span><%= flat.number_of_guests %></span>
              </div>
              <div class="price">
                <i class="fas fa-dollar-sign"></i>
                <span><%= flat.price_per_night %></span>
              </div>
            </div>
          </div>
          <div class="action">
            <%= link_to "More info", flat_path(flat), :class => "button-info" %>
            <%= link_to "Edit", edit_flat_path(flat), :class => "button-edit" %>
            <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' }, :class => "button-remove" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Simple Airbnb</a>
  <div class="ml-auto">
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
  </div>
</nav>

<div class="container">
  <%= simple_form_for @flat do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>
  <div class="form-actions">
    <%= f.submit 'Edit', class: 'btn btn-primary' %>
  </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Simple Airbnb</a>
  <div class="ml-auto">
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <a class="btn btn-outline-primary my-2 my-sm-0 ml-2" href="/flats/new">Add Flat</a>
  </div>
</nav>

<h1>Info flat</h1>
 <%= @flat.name %>
 <%= @flat.address %>
 <%= @flat.description %>
 <%= @flat.number_of_guests %>
 <%= @flat.price_per_night %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>